name: AtomicDEX Pro MacOS CI

on: [pull_request, push]

jobs:

  macos-build:
    name: MacOS Build
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install QT (MacOS)
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.14.2'
          host: 'mac'
          target: 'desktop'
          dir: '${{ github.workspace }}'
          modules: 'qtcharts qtwidgets debug_info'

      - name: Install deps (MacOS)
        run: |
          brew update
          brew upgrade
          brew install autoconf \
                       automake \
                       libtool \
                       pkgconfig \
                       wget \
                       nim \
                       cmake \
                       ninja \
                       git \
                       boost \
                       gcc

          # get libbitcoin
          git clone --depth 1 --branch version5 --single-branch "https://github.com/libbitcoin/secp256k1"
          cd secp256k1
          ./autogen.sh
          ./configure --disable-shared --disable-tests --enable-module-recovery
          make
          sudo make install
          cd ../

          git clone --depth 1 --branch version3 --single-branch https://github.com/KomodoPlatform/libbitcoin-system.git
          cd libbitcoin-system
          ./autogen.sh
          ./configure --with-boost --disable-shared
          make
          sudo make install
          sudo update_dyld_shared_cache

      - name: Build (MacOS)
        run: |
          export QT_INSTALL_CMAKE_PATH=${{ github.workspace }}/Qt/5.14.2/clang_64/lib/cmake
          export QT_ROOT=${{ github.workspace }}/Qt/5.14.2
          cd ci_tools_atomic_dex
          nimble build -y
          ./ci_tools_atomic_dex bundle debug
          ls bundle-Debug/atomicDEX-Pro.dmg

      - name: Upload artifacts (MacOS)
        uses: actions/upload-artifact@v1
        with:
          name: dexpro-mac-debug.dmd
          path: ./ci_tools_atomic_dex/bundle-Debug/atomicDEX-Pro.dmg
