name: AtomicDEX Pro MacOS CI

on: [pull_request, push]

jobs:

  macos-build:
    name: MacOS Build
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install QT (MacOS)
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.14.1'
          host: 'mac'
          target: 'desktop'
          dir: '${{ github.workspace }}'
          modules: 'qtcharts qtwidgets debug_info'

      - name: Install deps (MacOS)
        run: |
          ls -la ${{ github.workspace }}/Qt/5.14.1/clang_64/lib/cmake
          brew update
          brew upgrade
          brew install autoconf \
                       automake \
                       libtool \
                       pkgconfig \
                       wget \
                       nim \
                       cmake \
                       ninja \
                       git \
                       boost \
                       gcc

          # get libbitcoin
          wget https://raw.githubusercontent.com/KomodoPlatform/libbitcoin-system/version3/install.sh
          chmod +x install.sh
          sudo ./install.sh --prefix=/bitcoin/ --build-boost --disable-shared

      - name: Build (MacOS)
        env:
          QT_INSTALL_CMAKE_PATH: ${{ github.workspace }}/Qt/5.14.1/clang_64/lib/cmake
          QT_ROOT: ${{ github.workspace }}/Qt/5.14.1
        run: |
          cd ci_tools_atomic_dex
          ls -la
          nimble build -y
          ./ci_tools_atomic_dex build debug
          ls -la
          ./ci_tools_atomic_dex bundle debug
          ls -la

#      - name: Upload artifacts (MacOS)
#        uses: actions/upload-artifact@v1
#        with:
#          name: atomicdexpro-linux.tar.gz
#          path: ./tbd
